### ISSUE TITLE
HUAWEI y6(4a) is not msm8916

### ISSUE THREAD

**Issue by OPPO9008** [Huawei-Y6/manifest#1]
i am sorry for my English, but i want tell you:HUAWEI y6(make in 2015,Chinese say 4A)s cpu is msm8909。

**Comment by Thespartann** [comment]
Yes, it is not msm8916, but it's sources are actually based on msm8916 ones and modified for use with the Y6 as the chips are actually very similar.
I know i'm late, but whatever
